services:
  - type: web
    name: dccon-arca-discord-bot-server
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_PUBLIC_KEY
        sync: false
      - key: OAUTH_REDIRECT_URI
        sync: false
